Cure Clinic/Models/About.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cure_Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int Id { get; set; }
        public string DoctorName { get; set; }
        public string Definition { get; set; }
        public string DoctorPic { get; set; }
        public string Job { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}

Cure Clinic/Models/Blog.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cure_Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime PostDate { get; set; }
        public string PostText { get; set; }
        public string PostImg { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}

Cure Clinic/Models/Contact.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cure_Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsSeen { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}

Cure Clinic/Models/CureClinic.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Cure Clinic/Models/SubService.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cure_Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubService
    {
        public int Id { get; set; }
        public int MainServiceId { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string Image { get; set; }
    
        public virtual MainService MainService { get; set; }
    }
}

Cure Clinic/Controllers/CureClinicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cure_Clinic.Models;
using System.Web.Script.Serialization;

namespace Cure_Clinic.Controllers
{
    public class CureClinicController : Controller
    {
        CureClinicEntities db = new CureClinicEntities();

        #region Home
        public ActionResult Index()
        {
            var home = db.Homes.ToList();
            return View(home);
        }
        #endregion

        #region About
        public ActionResult About(int Id)
        {
            var doctors = db.Abouts.Where(d => d.Id == Id).FirstOrDefault();
            return View(doctors);
        }

        [HttpPost]
        public ActionResult About(FormCollection collection, HttpPostedFileBase DoctorImage)
        {
            int id = int.Parse(collection["Id"]);

            HttpPostedFileBase Image = Request.Files["DoctorPic"];

            About doctor = db.Abouts.Where(h => h.Id == id).FirstOrDefault();

            string Text = collection["Definition"];

            return View();
        }

        public ActionResult AboutAllDoctors()
        {
            var doctors = db.Abouts.ToList();
            return View(doctors);
        }
        #endregion

        #region Contact
        public ActionResult Contact()
        {
            var contact = db.Locations.FirstOrDefault();
            return View(contact);
        }

        [HttpPost]
        public ActionResult Contact(FormCollection collection)
        {
            string Name = collection["name"];
            string EmailAddress = collection["email"];
            string msg = collection["message"];

            Contact contactN = new Contact();
            contactN.Name = Name;
            contactN.Email = EmailAddress;
            contactN.Message = msg;
            contactN.Date = DateTime.Now;
            contactN.IsSeen = false;

            db.Contacts.Add(contactN);
            if (db.SaveChanges() > 0)
                return Json(new { success = true, message = "Sending Success" }, JsonRequestBehavior.AllowGet);
            else
                return Json(new { success = false, message = "Sending Falied" }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Service
        public ActionResult Services()
        {
            var services = db.MainServices.ToList();
            return View(services);
        }

        public ActionResult SubServices(int id)
        {
            var query = (from m in db.SubServices
                         where m.MainServiceId == id
                         select m.MainService.Title).FirstOrDefault();
            ViewBag.MainTitle = query;

            var results = db.SubServices.Where(s => s.MainServiceId == id).ToList();
            return View(results);
        }

        public ActionResult Details(int id)
        {
            var details = db.SubServices.Where(r => r.Id == id).FirstOrDefault();
            return View(details);
        }

        [HttpPost]
        public ActionResult Details(FormCollection collection, HttpPostedFileBase HospitalImage)
        {
            int id = int.Parse(collection["Id"]);

            HttpPostedFileBase Image = Request.Files["Image"];

            SubService hospital = db.SubServices.Where(h => h.Id == id).FirstOrDefault();

            string Text = collection["text"];

            return View();
        }
        #endregion

        #region Blog
        public ActionResult Blog()
        {
            var blog = db.Blogs.OrderByDescending(M => M.PostDate).ToList().Take(6);
            return View(blog);
        }

        public ActionResult PostDetails(int id)
        {
            var details = db.Blogs.Where(b => b.Id == id).FirstOrDefault();
            return View(details);
        }

        [HttpPost]
        public ActionResult PostDetails(FormCollection collection)
        {
            int PostId = Convert.ToInt32(collection["Id"]);
            string Comment = collection["Comment"];

            Comment comment = db.Comments.Where(C => C.Comment1 == Comment).FirstOrDefault();

            Comment commentN = new Comment();
            commentN.Comment1 = Comment;
            commentN.BlogId = PostId;
            commentN.CommentDate = DateTime.Now;

            db.Comments.Add(commentN);
            if (db.SaveChanges() > 0)
                return Json(new { success = true, message = "" }, JsonRequestBehavior.AllowGet);
            else
                return Json(new { success = false, message = "The comment was not saved" }, JsonRequestBehavior.AllowGet);
        }
        #endregion

    }
}

Cure Clinic/Views/CureClinic/About.cshtml
@model Cure_Clinic.Models.About
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section menu
{
    <ul id="responsivemenu" style="font-weight:bold;font-size:20px">
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Index"><i class="icon-home homeicon"></i><span class="showmobile">Home</span></a></li>
        <li class="active" style="color:#2ba6cb;"><a href="~/CureClinic/AboutAllDoctors">About</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Blog">Blog</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Services">Services</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Contact">Contact</a></li>
    </ul>
 }

<br/>
<div class="undermenuarea">
    <div class="boxedshadow">
    </div>
    <div class="grid">
        <div class="row">
            <div class="c8">
                <h1 class="titlehead">About</h1>
            </div>
            <div class="c4">
                <h1 class="titlehead rightareaheader"><i class="icon-book" style="font-size:20px">@Model.DoctorName</i></h1>
            </div>
        </div>
    </div>
</div>
<br />
                    <div class="grid">
                    <h1 style="font-size:20px;font-family:'Times New Roman';font-weight:bold">
                        <span style="font-weight:bold">More Details about :</span> 
                        <span style="font-weight:bold">@Model.DoctorName</span>
                    </h1>
             
                    <div class="row">
                        <div class="c4">

                        </div>
                        <div class="c4">
                            <img src="@Model.DoctorPic" style="width:70%;border-radius:10%;height:40%" />
                        </div>
                        <div class="c4">

                        </div>
                    </div>
                    <br />
                    <div class="row" style="font-size:16px;font-family:'Times New Roman';font-weight:bold;">
                            <div class="c2">
                             
                            </div>
                            <div class="c8" style="border:solid;border-color:#2ba6cb;border-radius:5px">
                                @Model.Definition
                            </div>
                            <div class="c2">

                            </div>
                        </div>
                    </div>
<br />
<div class="row">
    <div class="c10">

    </div>
    <div class="c2">
        <input type="button" class="button" style="font-size:15px;background-color:crimson" value="Back" onclick="location.href='@Url.Action("AboutAllDoctors", "CureClinic")'">
    </div>
</div>

Cure Clinic/Views/CureClinic/AboutAllDoctors.cshtml
@model IEnumerable<Cure_Clinic.Models.About>
@{
    ViewBag.Title = "AboutAllDoctors";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            max-width: 70%;
            max-height : 70%;
            margin: auto;
            text-align: center;
            font-family: arial;
        }

        .title {
            color: grey;
            font-size: 14px;
        }

        button {
            border: none;
            outline: 0;
            display: inline-block;
            padding: 8px;
            color: white;
            background-color: black;
            text-align: center;
            cursor: pointer;
            width: 100%;
            font-size: 18px;
            font-weight: bold;
        }
        /*a {
      text-decoration: none;
      font-size: 22px;
      color: black;
    }*/
        .anchor {
            text-decoration: none;
            font-size: 22px;
            color: black;
        }

        button:hover, anchor:hover {
            opacity: 0.7;
        }
</style>


@section menu
{
    <ul id="responsivemenu" style="font-weight:bold;font-size:20px">
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Index"><i class="icon-home homeicon"></i><span class="showmobile">Home</span></a></li>
        <li class="active" style="color:#2ba6cb;"><a href="~/CureClinic/AboutAllDoctors">About</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Blog">Blog</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Services">Services</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Contact">Contact</a></li>
    </ul>
}

<br />
<div class="undermenuarea">
    <div class="boxedshadow">
    </div>
    <div class="grid">
        <div class="row">
            <div class="c8">
                <h1 class="titlehead">Cure Clinic Staff</h1>
            </div>
        </div>
    </div>
</div>
<br /><br />
<div class="row">
    @{
        foreach (var item in Model)
        {
            <div class="c3">
                <div class="card">
                    <img src="@item.DoctorPic" style="width:100%;height:180px">
                    <h5>@item.DoctorName</h5>
                    <p class="title">@item.Job</p>
                    <p><button  onclick="location.href='@Url.Action("About", "CureClinic",new {Id=@item.Id})'">See More</button></p>
                </div>
            </div>
        }
    }
</div>

Cure Clinic/Views/CureClinic/Blog.cshtml
@model IEnumerable<Cure_Clinic.Models.Blog>
@{
    ViewBag.Title = "Blog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">

<style>
    body, h1, h2, h3, h4, h5 {
        font-family: "Raleway", sans-serif;
    }
</style>
<body class="w3-light-grey">


    @section menu
    {
        <ul id="responsivemenu" style="font-weight:bold;font-size:20px">
            <li style="color:#2ba6cb;"><a href="~/CureClinic/Index"><i class="icon-home homeicon"></i><span class="showmobile">Home</span></a></li>
            <li style="color:#2ba6cb;"><a href="~/CureClinic/AboutAllDoctors">About</a></li>
            <li class="active" style="color:#2ba6cb;"><a href="~/CureClinic/Blog">Blog</a></li>
            <li style="color:#2ba6cb;"><a href="~/CureClinic/Services">Services</a></li>
            <li style="color:#2ba6cb;"><a href="~/CureClinic/Contact">Contact</a></li>
        </ul>
    }

    <div class="w3-content" style="max-width:1400px">
        <br />
        <div class="undermenuarea">
            <div class="boxedshadow">
            </div>
            <div class="grid">
                <div class="row">
                    <div class="c8">
                        <h1 class="titlehead">Blog</h1>
                    </div>
                </div>
            </div>
        </div>

        <div class="c12">
            <div class="royalcontent">
                <h1 class="title" style="text-transform:none;color:crimson;font-size:30px;">--Welcome to the Homeopathic Medicine News--</h1>
            </div>
        </div>
        <!-- Grid -->
        <div class="w3-row">
            <!-- Blog entries -->
            <div class="w3-col l8 s12">
                @{
                    foreach (var item in Model)
                    {

                <!-- Blog entry -->
                        <div class="w3-card-4 w3-margin w3-white">
                            <img src="@item.PostImg" alt="Nature" style="width:100%;height:300px">
                            <div class="w3-container">
                                <h3><b>Dr. @item.User.UserName</b></h3>
                                <h5>@item.Title, <span class="w3-opacity">@item.PostDate</span></h5>
                            </div>

                            <div class="w3-container">
                                <p>
                                    @item.PostText.Substring(0,200)
                                </p>
                                <div class="w3-row">
                                    <div class="w3-col m8 s12">
                                        @*<p><button type="button" class="w3-button w3-padding-large w3-white w3-border" onclick="location.href='@item.Id"><b>READ MORE »</b></button></p>*@
                                        <p><a href="~/CureClinic/PostDetails/@item.Id" class="w3-button w3-padding-large w3-white w3-border"><b>READ MORE »</b></a></p>
                                    </div>
                                    @{
                                        Cure_Clinic.Models.CureClinicEntities db = new Cure_Clinic.Models.CureClinicEntities();
                                        int CommentsCount = db.Comments.Where(M => M.BlogId == item.Id).Count();

                                        <div class="w3-col m4 w3-hide-small">
                                            <p><span class="w3-padding-large w3-right"><b>Comments  </b> <span class="w3-tag">@CommentsCount</span></span></p>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                        <hr>
                                        }
                }
            </div>

            <!-- Introduction menu -->
            <div class="w3-col l4">
                <!-- Posts -->
                <div class="w3-card-2 w3-margin">

                    <div class="w3-container w3-padding">
                        <h4>Popular Posts</h4>
                    </div>
                    <ul class="w3-ul w3-hoverable w3-white">
                        @{
                            foreach (var item1 in Model)
                            {
                                <li class="w3-padding-16">
                                    <img src="@item1.PostImg" alt="Image" class="w3-left w3-margin-right" style="width:50px;height:33px">
                                    <span class="w3-large">Dr/@item1.User.UserName</span><br>
                                    <a href="~/CureClinic/PostDetails/@item1.Id"><span>@item1.Title</span></a>
                                </li>
                            }
                        }
                    </ul>
                </div>
                <hr>
            </div>
        </div><br>
    </div>
</body>

Cure Clinic/Views/CureClinic/Details.cshtml
@model Cure_Clinic.Models.SubService
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section menu
{
    <ul id="responsivemenu" style="font-weight:bold;font-size:20px">
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Index"><i class="icon-home homeicon"></i><span class="showmobile">Home</span></a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/AboutAllDoctors">About</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Blog">Blog</a></li>
        <li class="active" style="color:#2ba6cb;"><a href="~/CureClinic/Services">Services</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Contact">Contact</a></li>
    </ul>
}

<br />
<div class="undermenuarea">
    <div class="boxedshadow">
    </div>
    <div class="grid">
        <div class="row">
            <div class="c8">
                <h1 class="titlehead">@Model.Title</h1>
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="c3">

    </div>
    <div class="c8">
        <img src="@Model.Image" style="width:80%;border-radius: 50%;" />
    </div>
    <div class="c1">

    </div>
</div>
<br />
<div class="row">
    <div class="c2">

    </div>
    <div class="c8">
        <input id="Id" name="Id" value="@Model.Id" type="hidden" />
        <p id="text" style="font-size:22px;color:#00858e;text-indent: 50px;line-height:180%;text-align:left;">
            @Model.Text
        </p>
    </div>
    <div class="c2">

    </div>
</div>
<br />
<div class="row">
    <div class="c10">

    </div>
    <div class="c2">
        <br />
        <input type="button" class="button" style="font-size:12px;background-color:crimson;margin-left:85px" value="Back" onclick="location.href='@Url.Action("Services", "CureClinic")'">
    </div>
</div>

Cure Clinic/Views/CureClinic/PostDetails.cshtml
@model Cure_Clinic.Models.Blog
@{
    ViewBag.Title = "PostDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">

<link href="~/Contents/css/StyleSheet1.css" rel="stylesheet" />
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

<style>
    body, h1, h2, h3, h4, h5 {
        font-family: "Raleway", sans-serif;
    }
</style>

@section menu
    {
    <ul id="responsivemenu" style="font-weight:bold;font-size:20px">
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Index"><i class="icon-home homeicon"></i><span class="showmobile">Home</span></a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/AboutAllDoctors">About</a></li>
        <li class="active" style="color:#2ba6cb;"><a href="~/CureClinic/Blog">Blog</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Services">Services</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Contact">Contact</a></li>
    </ul>
}

<br />
<div class="undermenuarea">
    <div class="boxedshadow">
    </div>
    <div class="grid">
        <div class="row">
            <div class="c8">
                <h1 class="titlehead">Post Details & Comments</h1>
            </div>
        </div>
    </div>
</div>
<br />
<div class="grid">

    <div class="w3-row">
        <!-- Blog entry -->
        <div class="w3-card-4 w3-margin w3-white">
            
            <img src="@Model.PostImg" alt="Nature" style="width:100%;height:300px">
            <div class="w3-container">
                <h3><b>Dr. @Model.User.UserName</b></h3>
                <h5>@Model.Title, <span class="w3-opacity">@Model.PostDate</span></h5>
            </div>

            <div class="w3-container">
                <p>
                    @Model.PostText
                </p>
                <div class="w3-row">
                    <div class="w3-col m8 s12">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </div>
                        @{
                            Cure_Clinic.Models.CureClinicEntities db = new Cure_Clinic.Models.CureClinicEntities();
                            int CommentsCount = db.Comments.Where(M => M.BlogId == Model.Id).Count();

                            <div class="w3-col m4 w3-hide-small">
                                <p><span class="w3-padding-large w3-right"><b>Comments  </b> <span class="w3-tag">@CommentsCount</span></span></p>
                            </div>
                        }
                    </div>

                <hr>

                <form id="myForm" class="form-inline" role="form">
                    <div class="form-group" style="width:80%">
                        <input id="Id" name="Id" value="@Model.Id" type="hidden" />
                        <input id="Comment" name="Comment" class="form-control" type="text" style="width:100%" placeholder="Your comments" />
                    </div>
                    <div class="form-group" style="margin-right:20px">
                        <button id="btnSubmit" type="submit" class="btn btn-danger" style="color:white;width:90px">Add</button>
                    </div>
                    <br/>
                    <span id="MessageComment" style="font-size:12px; color:red"></span>
                </form>

                <hr>

                  <!-- Show Comments -->
                  @{
                    var Comments = db.Comments.Where(c => c.BlogId == Model.Id).OrderByDescending(M => M.Id).ToList();
                    foreach (var item in Comments)
                    {
                     <div class="w3-row">
                        <div class="w3-col l2 m3" style="width: 10.99999%;">
                            <img src="~/Contents/images/background/download.png" style="width:80px;height:80px" />
                        </div>
                        <div class="w3-col l10 m9">
                            <p>
                                <h5 style="font-size:18px;font-family:Arial">
                                    @item.Comment1<br />
                                    <span class="w3-opacity w3-medium">@item.CommentDate</span>
                                </h5>
                            </p>
                        </div>
                       <br />
                    </div>
                     <!-- End Comments -->
                    <hr>
                    }
                }
                </div>
        </div>
    </div>
 </div>
    @*<br />
        <div class="row">
            <div class="c10">

            </div>
            <div class="c2">
                <input type="button" class="button" style="font-size:12px;background-color:crimson" value="Back" onclick="location.href='@Url.Action(" AboutAllDoctors", "CureClinic" )'">
            </div>
        </div>*@

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script>
    function CheckInputs() {
        var Comment = document.getElementById("Comment").value;

        if (Comment != "") {
            return true;
        }
        else {
            document.getElementById("MessageComment").innerHTML = "";

            if (Comment == "") {
                document.getElementById("MessageComment").innerHTML = "Enter Your Comment";
            }
            return false;
        }
    }
</script>

<script>
    $(document).ready(function () {
        $('#myForm').on('submit', function (event) {
            event.preventDefault();
            if (!CheckInputs()) return false;
            $.ajax({
                url: '/CureClinic/PostDetails',
                type: 'post',
                data: $('#myForm').serialize(),
                dataType: "json",
                success: function (data) {
                    if (data.success) {
                        location.href = '@Url.Action("PostDetails", "CureClinic")';
                    }
                    else if (!data.success) {
                        document.getElementById("MessageComment").innerHTML = data.message;
                    }
                    $.each(data.Errors, function (key, value) {
                    });
                }
            });
        });
    });
</script>

Cure Clinic/Views/CureClinic/Services.cshtml
@model IEnumerable<Cure_Clinic.Models.MainService>
@{
    ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section menu
{
    <ul id="responsivemenu" style="font-weight:bold;font-size:20px">
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Index"><i class="icon-home homeicon"></i><span class="showmobile">Home</span></a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/AboutAllDoctors">About</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Blog">Blog</a></li>
        <li class="active" style="color:#2ba6cb;"><a href="~/CureClinic/Services">Services</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Contact">Contact</a></li>
    </ul>
}

<br />
<div class="undermenuarea">
    <div class="boxedshadow">
    </div>
    <div class="grid">
        <div class="row">
            <div class="c8">
                <h1 class="titlehead">Services</h1>
            </div>
        </div>
    </div>
</div>

<div class="row space-bot">
    <!--INTRO-->
    <div class="c3">

    </div>
    <div class="c6">
        <div class="royalcontent">
            @*<h1 class="title" style="text-transform:none;color:indianred;font-size:30px;">-- Our Services --</h1>*@
        </div>
    </div>
    <div class="c3">

    </div>

    @{
        foreach (var item in Model)
        {
            <div class="item">
                <div class="c4">
                    <br /><br />
                    <a href="~/CureClinic/SubServices/@item.Id" style="border-radius:30px; margin: 100px 89px;background-color:cadetblue;padding: 15px 32px;font-size: 20px;color:white">
                        @item.Title
                    </a>
                </div>
            </div>
        }
    }

</div>

Cure Clinic/Views/CureClinic/SubServices.cshtml
@model IEnumerable<Cure_Clinic.Models.SubService>
@{
    ViewBag.Title = "SubServices";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .boxstyle {
        background-color: lavender;
        width: 200px;
        height: 150px;
        padding: 40px 40px;
        text-align: center;
        box-shadow: 10px 10px 5px #888888;
    }

    .anchorstyle {
        font-size: 22px;
        font-family: 'Times New Roman';
        color: chocolate;
    }
</style>

@section menu
{
    <ul id="responsivemenu" style="font-weight:bold;font-size:20px">
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Index"><i class="icon-home homeicon"></i><span class="showmobile">Home</span></a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/AboutAllDoctors">About</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Blog">Blog</a></li>
        <li class="active" style="color:#2ba6cb;"><a href="~/CureClinic/Services">Services</a></li>
        <li style="color:#2ba6cb;"><a href="~/CureClinic/Contact">Contact</a></li>
    </ul>
}

<br />
<div class="undermenuarea">
    <div class="boxedshadow">
    </div>
    <div class="grid">
        <div class="row">
            <div class="c8">
                <h1 class="titlehead">@ViewBag.MainTitle</h1>
            </div>
        </div>
    </div>
</div>

<br /><br />

@{
    foreach (var item in Model)
    {
        <div class="item">
            <div class="c3" style="padding-left:50px">
                <br /><br />
                <div class="boxstyle">
                    <a href="~/CureClinic/Details/@item.Id" class="anchorstyle">@item.Title</a>
                </div>
            </div>
        </div>
    }
}

<br /><br />
<div class="row">
    <div class="c10">

    </div>
    <div class="c2">
        <br/>
        <input type="button" class="button" style="font-size:12px;background-color:crimson;margin-left:85px" value="Back" onclick="location.href='@Url.Action("Services", "CureClinic")'">
    </div>
</div>