Cure Clinic/Models/About.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cure_Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int Id { get; set; }
        public string DoctorName { get; set; }
        public string Definition { get; set; }
        public string DoctorPic { get; set; }
        public string Job { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}

Cure Clinic/Models/Blog.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cure_Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime PostDate { get; set; }
        public string PostText { get; set; }
        public string PostImg { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}

Cure Clinic/Models/Contact.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cure_Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsSeen { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}

Cure Clinic/Models/Location.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cure_Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    }
}

Cure Clinic/Controllers/adminController.cs
using Cure_Clinic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;
using System.Net.Mail;
using System.Net;
using System.Web.Mvc;
using Cure_Clinic;
using System.Data.Entity;

namespace DashBoard_CureClinic.Controllers
{
    public class adminController : Controller
    {
        //database entity 
        CureClinicEntities db = new CureClinicEntities();

        // GET: admin
        public ActionResult Index()
        {
            if (LogedUser.IsLoged() && LogedUser.CurrentUser().UserRole.RoleName == "User")
                return View();
            else
                return RedirectToAction("Login");
        }

        public ActionResult IndexAdmin()
        {
            if (LogedUser.IsLoged() && LogedUser.CurrentUser().UserRole.RoleName == "Admin")
                return View();
            else
                return RedirectToAction("Login");
        }

        #region Home
        public ActionResult HomeEditing()
        {
            return View();
        }

        public ActionResult Slider()
        {
            var slider = db.Homes.FirstOrDefault();
            if (LogedUser.IsLoged() && LogedUser.CurrentUser().UserRole.RoleName == "Admin")
                return View(slider);
            else
                return RedirectToAction("Login");
           
        }

        [HttpPost]
        public ActionResult Slider(FormCollection collection)
        {
            int HomeId = Convert.ToInt32(collection["HomeId"]);
            string SliderText1 = collection["SliderText1"];
            string SliderText2 = collection["SliderText2"];
            string SliderText3 = collection["SliderText3"];
            HttpPostedFileBase Image1 = Request.Files["Image1"];
            HttpPostedFileBase Image2 = Request.Files["Image2"];
            HttpPostedFileBase Image3 = Request.Files["Image3"];

            Home homeList = db.Homes.Where(s => s.Id == HomeId).FirstOrDefault();
            if(homeList != null)
            {
                if (homeList.SlideText1 != SliderText1 || homeList.SlideText2 != SliderText2 || homeList.SlideText3 != SliderText3)
                {
                    Home OldHome = db.Homes.Where(b => b.SlideText1 == SliderText1 && b.SlideText2 == SliderText2 
                                                    && b.SlideText3 == SliderText3).FirstOrDefault();
                    if(OldHome == null)
                    {
                        homeList.SlideText1 = SliderText1;
                        homeList.SlideText2 = SliderText2;
                        homeList.SlideText3 = SliderText3;
                       
                        if (Image1 != null && Image1.ContentLength > 0)
                        {
                            var rondom = Path.GetRandomFileName().Replace(".", "") + Path.GetExtension(Image1.FileName);
                            string path = Path.Combine(Server.MapPath("/Upload/HomeImage"), Path.GetFileName(rondom));
                            Directory.CreateDirectory(Server.MapPath("/Upload/HomeImage"));
                            Image1.SaveAs(path);

                            homeList.SlideImg1 = "/Upload/HomeImage/" + rondom;
                        }
                        if (Image2 != null && Image2.ContentLength > 0)
                        {
                            var rondom = Path.GetRandomFileName().Replace(".", "") + Path.GetExtension(Image2.FileName);
                            string path = Path.Combine(Server.MapPath("/Upload/HomeImage"), Path.GetFileName(rondom));
                            Directory.CreateDirectory(Server.MapPath("/Upload/HomeImage"));
                            Image2.SaveAs(path);
                            
                            homeList.SlideImg2 = "/Upload/HomeImage/" + rondom;
                        }
                        if (Image3 != null && Image3.ContentLength > 0)
                        {
                            var rondom = Path.GetRandomFileName().Replace(".", "") + Path.GetExtension(Image3.FileName);
                            string path = Path.Combine(Server.MapPath("/Upload/HomeImage"), Path.GetFileName(rondom));
                            Directory.CreateDirectory(Server.MapPath("/Upload/HomeImage"));
                            Image3.SaveAs(path);
                            
                            homeList.SlideImg3 = "/Upload/HomeImage/" + rondom;
                        }
                        if (db.SaveChanges() > 0)
                            return Json(new { success = true, message = "" }, JsonRequestBehavior.AllowGet);
                        else
                            return Json(new { success = false, message = "The Text was not Edited" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                        return Json(new { success = false, message = "This Text was previously saved" }, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json(new { success = true, message = "" }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { success = false, message = "" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Boxes()
        {
            var homebox = db.HomeBoxes.FirstOrDefault();
            if (LogedUser.IsLoged() && LogedUser.CurrentUser().UserRole.RoleName == "Admin")
                return View(homebox);
            else
                return RedirectToAction("Login");
        }

        [HttpPost]
        public ActionResult Boxes(FormCollection collection)
        {
            int HomeBoxId = Convert.ToInt32(collection["HomeBoxId"]);
            string Text1 = collection["Text1"];
            string Text2 = collection["Text2"];
            string Text3 = collection["Text3"];
            HttpPostedFileBase Image1 = Request.Files["Image1"];
            HttpPostedFileBase Image2 = Request.Files["Image2"];
            HttpPostedFileBase Image3 = Request.Files["Image3"];
            HomeBox homeList = db.HomeBoxes.Where(s => s.Id == HomeBoxId).FirstOrDefault();
            if (homeList != null)
            {
                if (homeList.Text1 != Text1 || homeList.Text2 != Text2 || homeList.Text3 != Text3)
                {
                    HomeBox OldHome = db.HomeBoxes.Where(b => b.Text1 == Text1 && b.Text2 == Text2
                                                    && b.Text3 == Text3).FirstOrDefault();
                    if (OldHome == null)
                    {
                        homeList.Text1 = Text1;
                        homeList.Text2 = Text2;
                        homeList.Text3 = Text3;

                        if (Image1 != null && Image1.ContentLength > 0)
                        {
                            var rondom = Path.GetRandomFileName().Replace(".", "") + Path.GetExtension(Image1.FileName);
                            string path = Path.Combine(Server.MapPath("/Upload/HomeBoxImage"), Path.GetFileName(rondom));
                            Directory.CreateDirectory(Server.MapPath("/Upload/HomeBoxImage"));
                            Image1.SaveAs(path);

                            homeList.Img1 = "/Upload/HomeBoxImage/" + rondom;
                        }
                        if (Image2 != null && Image2.ContentLength > 0)
                        {
                            var rondom = Path.GetRandomFileName().Replace(".", "") + Path.GetExtension(Image2.FileName);
                            string path = Path.Combine(Server.MapPath("/Upload/HomeBoxImage"), Path.GetFileName(rondom));
                            Directory.CreateDirectory(Server.MapPath("/Upload/HomeBoxImage"));
                            Image2.SaveAs(path);

                            homeList.Img2 = "/Upload/HomeBoxImage/" + rondom;
                        }
                        if (Image3 != null && Image3.ContentLength > 0)
                        {
                            var rondom = Path.GetRandomFileName().Replace(".", "") + Path.GetExtension(Image3.FileName);
                            string path = Path.Combine(Server.MapPath("/Upload/HomeBoxImage"), Path.GetFileName(rondom));
                            Directory.CreateDirectory(Server.MapPath("/Upload/HomeBoxImage"));
                            Image3.SaveAs(path);

                            homeList.Img3 = "/Upload/HomeBoxImage/" + rondom;
                        }
                        if (db.SaveChanges() > 0)
                            return Json(new { success = true, message = "" }, JsonRequestBehavior.AllowGet);
                        else
                            return Json(new { success = false, message = "The Text was not Edited" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                        return Json(new { success = false, message = "This Text was previously saved" }, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json(new { success = true, message = "" }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { success = false, message = "" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Gallery()
        {
            var home = db.Homes.FirstOrDefault();
            if (LogedUser.IsLoged() && LogedUser.CurrentUser().UserRole.RoleName == "Admin")
                return View(home);
            else
                return RedirectToAction("Login");
        }

        [HttpPost]
        public ActionResult Gallery(FormCollection collection)
        {
            int HomeId = Convert.ToInt32(collection["HomeId"]);
            HttpPostedFileBase Image1 = Request.Files["Image1"];
            HttpPostedFileBase Image2 = Request.Files["Image2"];
            HttpPostedFileBase Image3 = Request.Files["Image3"];
            HttpPostedFileBase Image4 = Request.Files["Image4"];

Cure Clinic/Views/admin/About.cshtml
@model Cure_Clinic.Models.About
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>About</title>
</head>
<body>
    <div id="wrapper">
        @section menu
        {
        <ul class="nav navbar-nav side-nav">
            <li>
                <a href="Index"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
            </li>
            <li class="active">
                <a href="CureClinicStaff"><i class="fa fa-fw fa-pencil"></i> About</a>
            </li>
            <li>
                <a href="Blog"><i class="fa fa-fw fa-edit"></i> Blog</a>
            </li>
            <li>
                <a href="Services"><i class="fa fa-fw fa-desktop"></i> Services</a>
            </li>
         </ul>
        }

        <div id="page-wrapper">
            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h2 class="page-header">
                            @Model.DoctorName
                        </h2>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="Index">Dashboard</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-pencil"></i> About
                            </li>
                        </ol>
                    </div>
                </div>
                <form id="myForm" method="post">
                    <div class="row">
                        <div class="col-md-1">

                        </div>
                        <div class="col-md-11">
                            <p style="font-weight:bold;font-size:20px">Choose Picture :</p>
                            <br />
                            <img src="@Model.DoctorPic" style="width:20%;border-radius: 50%;" />
                            <br /><br />
                            <input type="file" name="Image" id="Image" />
                            <span id="MessageImage" style="font-size:12px; color:red"></span>
                            
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-1">

                        </div>
                        <div class="col-md-8">
                            <p style="font-weight:bold;font-size:20px">About @Model.DoctorName:</p>
                            <input id="AboutId" name="AboutId" value="@Model.Id" type="hidden" />
                            <textarea id="Text" name="Text" rows="7" cols="100" placeholder="Enter About Text" style="width:100%;height:100%">
                                @Model.Definition
                            </textarea>
                            <span id="MessageText" style="font-size:12px; color:red"></span>
                            <hr />
                            <br /><br />
                            <div>
                                <input id="btn_save" type="submit" value="Save" class="btn btn-danger" style="background:brown;color:white" />
                                <input id="btn_cancle" type="button" value="Cancle" class="btn btn-danger" style="background:brown;color:white" onclick="location.href='@Url.Action("CureClinicStaff", "admin")'" />
                            </div>
                        </div>
                        <div class="col-md-3">

                        </div>
                    </div>
                </form>
            </div>
        </div>
</div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

    <script>
    function CheckInputs() {
        var Text = document.getElementById("Text").value;
        if (Text != "")
        {
            return true;
        }
        else
        {
            document.getElementById("MessageText").innerHTML = "";
            if (Text == "")
            {
                document.getElementById("MessageText").innerHTML = "Enter About Text";
            }
            return false;
        }
    }
    </script>


    <script>
    $(document).ready(function () {
        $('#myForm').on('submit', function (event) {
            event.preventDefault();
            var formData = new FormData($('form')[0]);
            if (!CheckInputs()) return false;
            $.ajax({
                url: '/admin/About',
                type: 'post',
                data: $('#myForm').serialize(),
                data: formData,
                dataType: "json",
                cache: false,
                contentType: false,
                processData: false,
                success: function (data) {
                    if (data.success) {
                        location.href = '@Url.Action("CureClinicStaff", "admin")';
                    }
                    else if (!data.success) {
                        document.getElementById("MessageName").innerHTML = data.message;
                    }
                    $.each(data.Errors, function (key, value) {
                    });
                }
            });
        });
    });
    </script>

</body>
</html>

Cure Clinic/Views/admin/AddBlog.cshtml
@using Cure_Clinic.Models;
@{CureClinicEntities db = new CureClinicEntities();}
@{
    ViewBag.Title = "AddBlog";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Add Blog</title>
</head>
<body>
    <div id="wrapper">
        @section menu
        {
        <ul class="nav navbar-nav side-nav">
            <li>
                <a href="Index"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
            </li>
            <li>
                <a href="CureClinicStaff"><i class="fa fa-fw fa-pencil"></i> About</a>
            </li>
            <li class="active">
                <a href="Blog"><i class="fa fa-fw fa-edit"></i> Blog</a>
            </li>
            <li>
                <a href="Services"><i class="fa fa-fw fa-desktop"></i> Services</a>
            </li>
         </ul>
        }

        <div id="page-wrapper">
            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Add Blog
                        </h1>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-edit"></i>  <a href="Blog">Blog</a>
                            </li>
                            <li class="active">
                                AddBlog
                            </li>
                        </ol>
                    </div>
                </div>

                <form id="myForm" method="post">
                    <div class="row">
                        <div class="col-md-1">

                        </div>
                        <div class="col-md-11">
                            <p style="font-weight:bold;font-size:20px">Choose Picture :</p>
                            <br />
                            <input type="file" name="Image" id="Image" />
                            <span id="MessageImage" style="font-size:12px; color:red"></span>
                            <hr />
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-1">

                        </div>
                        <div class="col-md-11">
                            <p style="font-weight:bold;color:brown;font-size:15px">Title</p>
                            <input id="Title" name="Title" type="text" placeholder="Enter Post Title" style="width:250px"/>
                            <br />
                            <span id="MessageName" style="font-size:12px; color:red"></span>
                            <hr />
                            <p style="font-weight:bold;color:brown;font-size:15px">Text</p>
                            <textarea id="Text" name="Text" rows="7" cols="80" placeholder="Enter Post Text" style="width:80%;height:100%"></textarea>
                            <br />
                            <span id="MessageText" style="font-size:12px; color:red"></span>
                            <br /><br />
                            <div>
                                <input id="btn_save" type="submit" value="Save" class="btn btn-danger" style="background:brown;color:white" />
                                <input id="btn_cancle" type="button" value="Cancle" onclick="location.href='@Url.Action("Blog", "admin")';" class="btn btn-danger" style="background:brown;color:white" />
                            </div>
                        </div>
                    </div>
                </form>
             </div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

    <script>
    function CheckInputs() {
        var Title = document.getElementById("Title").value;
        var Text = document.getElementById("Text").value;

        if (Title != "" && Text != "") {
            return true;
        }
        else {
            document.getElementById("MessageName").innerHTML = "";
            document.getElementById("MessageText").innerHTML = "";

            if (Title == "") {
                document.getElementById("MessageName").innerHTML = "Enter Post Title";
            }
            if (Text == "") {
                document.getElementById("MessageText").innerHTML = "Enter Post Text";
            }
            return false;
        }
    }
    </script>
    <script>
    $(document).ready(function () {
        $('#myForm').on('submit', function (event) {
            event.preventDefault();
            var formData = new FormData($('form')[0]);
            if (!CheckInputs()) return false;
            $.ajax({
                url: '/admin/AddBlog',
                type: 'post',
                data: $('#myForm').serialize(),
                data: formData,
                dataType: "json",
                cache: false,
                contentType: false,
                processData: false,
                success: function (data) {
                    if (data.success) {
                        location.href = '@Url.Action("Blog", "admin")';
                    }
                    else if (!data.success) {
                        document.getElementById("MessageName").innerHTML = data.message;
                    }
                    $.each(data.Errors, function (key, value) {
                    });
                }
            });
        });
    });
    </script>

</body>
</html>

Cure Clinic/Views/admin/AddLocation.cshtml
@{
    ViewBag.Title = "AddLocation";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Add Location</title>
</head>
<body>
    <div id="wrapper">
        @section menu
        {
            <ul class="nav navbar-nav side-nav">
                <li>
                    <a href="IndexAdmin"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                </li>
                <li>
                    <a href="HomeEditing"><i class="fa fa-fw fa-home"></i> Home</a>
                </li>
                <li class="active">
                    <a href="Location"><i class="fa fa-map-marker"></i> Location</a>
                </li>
            </ul>
        }

        <div id="page-wrapper">
            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Location
                        </h1>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="IndexAdmin">Dashboard</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-map-marker"></i> Location
                            </li>
                        </ol>
                    </div>
                </div>

                <br />
                <div class="row">
                    <div class="col-md-1">

                    </div>
                    <form id="myForm" method="post">
                        <div class="col-md-11">

                            <p style="font-weight:bold;color:brown;font-size:15px">Address</p>
                            <textarea id="Address" name="Address" rows="3" cols="50" placeholder="Enter Address" style="width:50%;height:100%"></textarea>
                            <br />
                            <span id="MessageAddress" style="font-size:12px; color:red"></span>

                            <hr />
                            <p style="font-weight:bold;color:brown;font-size:15px">Telephone</p>
                            <input id="Phone" name="Phone" type="text" placeholder="Enter Phone Number" style="width:280px" />
                            <br />
                            <span id="MessagePhone" style="font-size:12px; color:red"></span>

                            <hr />
                            <p style="font-weight:bold;color:brown;font-size:15px">E-mail</p>
                            <input id="Email" name="Email" type="text" placeholder="Enter Email Address" style="width:280px"/>
                            <br />
                            <span id="MessageEmail" style="font-size:12px; color:red"></span>

                            <br /><br />
                            <div>
                                <input id="btn_save" type="submit" value="Save" class="btn btn-danger" style="background:brown;color:white" />
                                <input id="btn_cancle" type="button" value="Cancle" onclick="location.href='IndexAdmin';" class="btn btn-danger" style="background:brown;color:white" />
                            </div>
                            <br /><br />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

    <script>
    function CheckInputs() {
        var Address = document.getElementById("Address").value;
        var Phone = document.getElementById("Phone").value;
        var Email = document.getElementById("Email").value;

        if (Address != "" && Phone != "" && Email != "") {
            return true;
        }
        else
        {
            document.getElementById("MessageAddress").innerHTML = "";
            document.getElementById("MessagePhone").innerHTML = "";
            document.getElementById("MessageEmail").innerHTML = "";
            if (Address == "") {
                document.getElementById("MessageAddress").innerHTML = "Enter Address";
            }
            if (!checkPhone()) {
                document.getElementById("MessagePhone").innerHTML = "Please Enter Correct Phone Number";
            }
            if (Phone == "") {
                document.getElementById("MessagePhone").innerHTML = "Enter Phone Number";
            }
            if (!IsValidEmail(Email))
            {
                document.getElementById("MessageEmail").innerHTML = "Please Enter Correct Email ";
            }
            if (Email == "") {
                document.getElementById("MessageEmail").innerHTML = "Enter Email";
            }
        return false;
      }
    }
    </script>

    <script>
    $(document).ready(function () {
        $('#myForm').on('submit', function (event) {
            event.preventDefault();
            if (!CheckInputs()) return false;
            $.ajax({
                url: '/admin/AddLocation',
                type: 'post',
                data: $('#myForm').serialize(),
                dataType: "json",
                success: function (data) {
                    if (data.success) {
                        location.href = '@Url.Action("/IndexAdmin", "admin")';
                    }
                    else if (!data.success) {
                        document.getElementById("MessageAddress").innerHTML = data.message;
                    }
                    $.each(data.Errors, function (key, value) {
                    });
                }
            });
        });
    });
    </script>

    <script type="text/javascript">
    function IsValidEmail(Email)
    {
        var expr = /^([\w-\.]+)@@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
        return expr.test(Email);
    };
    </script>

    <script type="text/javascript">
    function checkPhone() {
        var phone = document.getElementById("Phone");
        var phoneNum = "^01[0-2][0-9]{8}$";
        return phone.value.match(phoneNum);
    };
    </script>
</body>
</html>